2017-05-24 17:01:12.059 [error] <0.296.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.301.0> exit with reason normal in context child_terminated
2017-05-24 17:01:25.056 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 17:59:29.038 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 18:04:03.307 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:04:41.237 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:05:47.375 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:07:22.063 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:09:51.331 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:11:29.931 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:12:05.989 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:12:15.748 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:15:50.058 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:31:15.767 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:31:25.762 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:32:01.759 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:32:11.457 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:32:58.005 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 18:33:09.141 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:35:19.295 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 18:46:39.536 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 18:49:19.193 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 18:50:56.413 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 19:12:05.169 [error] <0.253.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.258.0> exit with reason normal in context child_terminated
2017-05-24 19:12:36.359 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 19:13:54.456 [error] <0.229.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.234.0> exit with reason normal in context child_terminated
2017-05-24 19:14:18.253 [error] <0.420.0> CRASH REPORT Process <0.420.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Bot.Skill.Hello':casts() in gen_server:init_it/6 line 352
2017-05-24 19:14:18.253 [error] <0.419.0> CRASH REPORT Process <0.419.0> with 0 neighbours exited with reason: no match of right hand value {error,{undef,[{'Elixir.Bot.Skill.Hello',casts,[],[]},{'Elixir.Bot.Skill.Wrapper',init,1,[{file,"lib/bot/skill/wrapper.ex"},{line,14}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in 'Elixir.Bot.Skill.Delay':handle_info/2 line 14 in gen_server:init_it/6 line 352
2017-05-24 19:19:37.769 [error] <0.245.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.250.0> exit with reason normal in context child_terminated
2017-05-24 19:20:50.265 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 19:21:19.325 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 19:22:08.793 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 19:22:10.851 [error] <0.441.0> ** Task <0.441.0> terminating
** Started from <0.435.0>
** When function  == #Fun<Elixir.Bot.Skill.Hello.0.26567824>
**      arguments == []
** Reason for termination == 
** {{badmap,nil},[{maps,remove,[key,nil],[]},{'Elixir.Bot',wait,3,[{file,"lib/bot.ex"},{line,75}]},{'Elixir.Bot.Skill.Hello','-handle_cast/3-fun-1-',2,[{file,"lib/bot/sample/hello.ex"},{line,23}]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,85}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2017-05-24 19:22:10.860 [error] <0.441.0> CRASH REPORT Process <0.441.0> with 1 neighbours exited with reason: {{badmap,nil},[{maps,remove,[key,nil],[]},{'Elixir.Bot',wait,3,[{file,"lib/bot.ex"},{line,75}]},{'Elixir.Bot.Skill.Hello','-handle_cast/3-fun-1-',2,[{file,"lib/bot/sample/hello.ex"},{line,23}]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,85}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]} in 'Elixir.Task.Supervised':exit/4 line 116
2017-05-24 19:22:20.512 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 19:26:08.731 [error] <0.217.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.222.0> exit with reason normal in context child_terminated
2017-05-24 19:26:16.630 [error] <0.217.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.222.0> exit with reason normal in context child_terminated
2017-05-24 19:37:13.378 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.207.0> exit with reason normal in context child_terminated
2017-05-24 20:50:27.703 [error] <0.247.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.252.0> exit with reason normal in context child_terminated
2017-05-24 20:51:49.129 [error] <0.235.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.240.0> exit with reason normal in context child_terminated
